In [4]:
import pandas as pd 
import numpy as np

In [13]:
df = pd.read_csv('./银行营销响应数据集（认购存款）.csv')
print('数据信息: ', df.shape)
df.head()

数据信息:  (11162, 17)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [14]:
df['deposit'] = df['deposit'].str.lower().replace({'no': 0, 'yes': 1})
df['id'] =list(np.arange(1,len(df)+1))
df.to_csv('./train.csv',encoding='utf8')
# df = df.rename(columns = {'deposit':'TARGET'})
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit,id
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,1,1
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,1,2
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,1,3
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,1,4
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,1,5

In [29]:
import scorecardpy as sc

In [30]:
dat = sc.germancredit()
dat['creditability'] = dat['creditability'].str.lower().replace({'bad': 0, 'good': 1})
dat.head()

,status.of.existing.checking.account,duration.in.month,credit.history,purpose,credit.amount,savings.account.and.bonds,present.employment.since,installment.rate.in.percentage.of.disposable.income,personal.status.and.sex,other.debtors.or.guarantors,...,property,age.in.years,other.installment.plans,housing,number.of.existing.credits.at.this.bank,job,number.of.people.being.liable.to.provide.maintenance.for,telephone,foreign.worker,creditability
0,... < 0 DM,6,critical account/ other credits existing (not ...,radio/television,1169,unknown/ no savings account,... >= 7 years,4,male : divorced/separated,none,...,real estate,67,none,own,2,skilled employee / official,1,"yes, registered under the customers name",yes,1
1,0 <= ... < 200 DM,48,existing credits paid back duly till now,radio/television,5951,... < 100 DM,1 <= ... < 4 years,2,male : divorced/separated,none,...,real estate,22,none,own,1,skilled employee / official,1,none,yes,0
2,no checking account,12,critical account/ other credits existing (not ...,education,2096,... < 100 DM,4 <= ... < 7 years,2,male : divorced/separated,none,...,real estate,49,none,own,1,unskilled - resident,2,none,yes,1
3,... < 0 DM,42,existing credits paid back duly till now,furniture/equipment,7882,... < 100 DM,4 <= ... < 7 years,2,male : divorced/separated,guarantor,...,building society savings agreement/ life insur...,45,none,for free,1,skilled employee / official,2,none,yes,1
4,... < 0 DM,24,delay in paying off in the past,car (new),4870,... < 100 DM,1 <= ... < 4 years,3,male : divorced/separated,none,...,unknown / no property,53,none,for free,2,skilled employee / official,2,none,yes,0

In [31]:
# filter variable via missing rate, iv, identical value rate
dt_s = sc.var_filter(dat, y="creditability")
dt_s['id'] =list(np.arange(1,len(dt_s)+1))
dt_s.to_csv('./train.csv',encoding='utf8')
print(dt_s.shape)
dt_s.head()

[INFO] filtering variables ...
(1000, 15)

,credit.history,other.installment.plans,credit.amount,savings.account.and.bonds,present.employment.since,status.of.existing.checking.account,other.debtors.or.guarantors,housing,installment.rate.in.percentage.of.disposable.income,property,purpose,age.in.years,duration.in.month,creditability,id
0,critical account/ other credits existing (not ...,none,1169,unknown/ no savings account,... >= 7 years,... < 0 DM,none,own,4,real estate,radio/television,67,6,1,1
1,existing credits paid back duly till now,none,5951,... < 100 DM,1 <= ... < 4 years,0 <= ... < 200 DM,none,own,2,real estate,radio/television,22,48,0,2
2,critical account/ other credits existing (not ...,none,2096,... < 100 DM,4 <= ... < 7 years,no checking account,none,own,2,real estate,education,49,12,1,3
3,existing credits paid back duly till now,none,7882,... < 100 DM,4 <= ... < 7 years,... < 0 DM,guarantor,for free,2,building society savings agreement/ life insur...,furniture/equipment,45,42,1,4
4,delay in paying off in the past,none,4870,... < 100 DM,1 <= ... < 4 years,... < 0 DM,none,for free,3,unknown / no property,car (new),53,24,0,5